let agentdata = [
    { 'relv': 'N/A', 'Rel': 'NAVARRO, ELMER A' },
    { 'relv': 'LeonardDORIN121988@gmail.com', 'Rel': 'DORIN, LEONARD V' },
    { 'relv': 'gumbannoel8@gmail.com', 'Rel': 'GUMBAN, NOEL L' },
    { 'relv': 'sangariosvonbryann@gmail.com', 'Rel': 'SANGARIOS, VON BRYAN P' },
    { 'relv': 'dennisapiladz@gmail.com', 'Rel': 'APILADO, DENNIS R' },
    { 'relv': 'danieapiladz@gmail.com', 'Rel': 'APILADO, DANIE R' },
    { 'relv': 'rizaldivicenti@gmail.com', 'Rel': 'VICENTE, RIZALDI F' },
    { 'relv': 'dongberong@gmail.com', 'Rel': 'BERONG, EUTIQUIO L' },
    { 'relv': 'N/A', 'Rel': 'TIBAY, RONNEL N' },
    { 'relv': 'klengbatucal@yahoo.com', 'Rel': 'BATUCAL, JAMESON G' },
    { 'relv': 'N/A', 'Rel': 'BAUTISTA, MARILOU P' },
    { 'relv': 'N/A', 'Rel': 'NAVARRO, ROEL A' },
    { 'relv': 'N/A', 'Rel': 'GUMBAN, BEVERLYN E' },
    { 'relv': 'RhoyAndal@gmail.com', 'Rel': 'ANDAL, RHOY D' },
    { 'relv': 'N/A', 'Rel': 'DOLDOLIA, FERDINAN E' },
    { 'relv': 'cpolido88@gmail.com', 'Rel': 'POLIDO, CINDY L' },
    { 'relv': 'algenberong@gmail.com', 'Rel': 'BERONG, ALGEN S' },
    { 'relv': 'N/A', 'Rel': 'MABOLES, JOHNNY RUSSEL J' },
    { 'relv': 'olivarronel@gmail.com', 'Rel': 'OLIVAR, RONEL E' },
    { 'relv': 'Hooby_Sb@yahoo.com', 'Rel': 'TABAOSARES, SUNNY BOY G' },
    { 'relv': 'N/A', 'Rel': 'BERGUNDO, JAMES A' },
    { 'relv': 'lapazkenneth169@gmail.com', 'Rel': 'LAPAZ, KENNETH P' },
    { 'relv': 'jeanissaadlaon11206@gmail.com', 'Rel': 'ADLAON, JEANISSA L' },
    { 'relv': 'N/A', 'Rel': 'LABESORES, CHRISTOPHER P' },
    { 'relv': 'eldonpiaca@yahoo.com', 'Rel': 'PIACA, ELDON C' },
    { 'relv': 'ocampomanilyn93@gmail.com', 'Rel': 'OCAMPO, MANILYN M' },
    { 'relv': 'N/A', 'Rel': 'TAJON, MELOJEAN V' },
    { 'relv': 'N/A', 'Rel': 'GARZON, ZENAIDA C' },
    { 'relv': 'nzulieta@yahoo.com', 'Rel': 'BALDO, NYSSA Z' },
    { 'relv': 'N/A', 'Rel': 'BALONA, JOSEPHINE G' },
    { 'relv': 'N/A', 'Rel': 'BUENCONSEJO, NILO I' },
    { 'relv': 'LeeFranz73@gmail.com', 'Rel': 'FRANCISCO, ROSALIE D' },
    { 'relv': 'N/A', 'Rel': 'MANAGO, LILIAN A' },
    { 'relv': 'vincentpalencia12', 'Rel': 'PALENCIA, VINCENT 0' },
    { 'relv': 'gpadept.mamsltg@gmail.com', 'Rel': 'DOLINOG, ANJENETTE M' },
    { 'relv': 'N/A', 'Rel': 'ORATE, RANNIE H' },
    { 'relv': 'N/A', 'Rel': 'GONZALES, REX A' },
    { 'relv': 'gracitaperico@gmail.com', 'Rel': 'PERICO, GRACITA R' },
    { 'relv': 'MarvDetomas099@gmail.com', 'Rel': 'DE TOMAS, MARVIN L' },
    { 'relv': 'angelomercado452@gmail.com', 'Rel': 'MERCADO, MARK ANGELO T' },
    { 'relv': 'elojajuliefer@yahoo.com', 'Rel': 'ELOJA, JULIEFER S' },
    { 'relv': 'jenpascual@gmail.com', 'Rel': 'ENCARNADO, JEANETTE O' },
    { 'relv': 'jinjinpendon@gmail.com', 'Rel': 'PENDON, MARY JANE D' },
    { 'relv': 'N/A', 'Rel': 'CEQUENA, BONIFACIA C' },
    { 'relv': 'jollideefebrer22@gmail.com', 'Rel': 'DIMACALI, JOLLIDEE F' },
    { 'relv': 'abbariaomariann25@gmail.com', 'Rel': 'ABBARIAO, MARY ANN J' },
    { 'relv': 'jie_pascual@yahoo.com', 'Rel': 'WALLESTAD, JESSICA P' },
    { 'relv': 'abramtravelandforum@yahoo.com', 'Rel': 'ARANETA, JULIET P' },
    { 'relv': 'N/A', 'Rel': 'GARIMBAO, VENUS D' },
    { 'relv': 'val.garidan@gmail.com', 'Rel': 'GARIDAN, VAL R' },
    { 'relv': 'N/A', 'Rel': 'TOLENTINO, MARILOU M' },
    { 'relv': 'N/A', 'Rel': 'PATIO, SIMPLICIO JR A' },
    { 'relv': 'N/A', 'Rel': 'MARCELO, VILMA N' },
    { 'relv': 'tutc_27@yahoo.com', 'Rel': 'PANLILIO, TUTCHIE C' },
    { 'relv': 'charlenemarcelo@gmail.com', 'Rel': 'MARCELO, CHARLENE N' },
    { 'relv': 'thems_720@yahoo.com', 'Rel': 'CARATIQUIT, THELMA V' },
    { 'relv': 'anne_gamis@yahoo.com', 'Rel': 'GAMIS, ANNALIZA A' },
    { 'relv': 'N/A', 'Rel': 'DELA CRUZ, RYAN V' },
    { 'relv': 'N/A', 'Rel': 'CARATIQUIT, JOSEFINA T' },
    { 'relv': 'N/A', 'Rel': 'DE JESUS, MARILOU G' },
    { 'relv': 'cristyadelante@gmail.com', 'Rel': 'ADELANTE, CRISTINA R' },
    { 'relv': 'almacmanalang@yahoo.com', 'Rel': 'MANALANG, ALMA C' },
    { 'relv': 'N/A', 'Rel': 'GUADEZ, SAMUEL D' },
    { 'relv': 'N/A', 'Rel': 'GONZALES, GABBY B' },
    { 'relv': 'laorcilada123@gmail.com', 'Rel': 'ORCILADA, LELANIE A' },
    { 'relv': 'elminda24@yahoo.com', 'Rel': 'ESCANO, MINDA D' },
    { 'relv': 'N/A', 'Rel': 'CASASOLA, ANNABELLE B' },
    { 'relv': 'N/A', 'Rel': 'DE JESUS, ROWENA R' },
    { 'relv': 'N/A', 'Rel': 'JAVIER, RACHEL D' },
    { 'relv': 'N/A', 'Rel': 'MARCELO, RAFAEL N' },
    { 'relv': 'yarcia_adelina@yahoo.com', 'Rel': 'YARCIA, ADELINA C' },
    { 'relv': 'N/A', 'Rel': 'PINLAC, EUSEBIO L' },
    { 'relv': 'o_verceles@yahoo.com', 'Rel': 'VERCELES, OLIVIA B' },
    { 'relv': 'N/A', 'Rel': 'CASASOLA, JOHN JOSEPH A' },
    { 'relv': 'N/A', 'Rel': 'PADILLA, MARIBEL M' },
    { 'relv': 'N/A', 'Rel': 'ANGWAY, ROSEMARIE M' },
    { 'relv': 'N/A', 'Rel': 'ANGWAY, JOEL N' },
    { 'relv': 'N/A', 'Rel': 'DANTES, SHARON M' },
    { 'relv': 'N/A', 'Rel': 'DONA, RICKY O' },
    { 'relv': 'N/A', 'Rel': 'GADIA, JANITTE V' },
    { 'relv': 'jashrivera10@gmail.com', 'Rel': 'RIVERA, JANICE J' },
    { 'relv': 'dalamemdech.32@yahoo.com', 'Rel': 'REPOLLO, AMELIA A' },
    { 'relv': 'aly110207@gmail.com', 'Rel': 'ABAD, CAROLINE R' },
    { 'relv': 'laarni_malanum@yahoo.com', 'Rel': 'MALANUM, LAARNIE C' },
    { 'relv': 'pelitosheryl@yahoo.com', 'Rel': 'PELITO, SHERYL C' },
    { 'relv': 'mayflor.rivera@yahoo.com', 'Rel': 'RIVERA, MAYFLOR J' },
    { 'relv': 'N/A', 'Rel': 'DIZON, JOSELINDA C' },
    { 'relv': 'N/A', 'Rel': 'BATTAD, BENILDA P' },
    { 'relv': 'zara.josephine@gmail.com', 'Rel': 'ZARA, JOSEPHINE J' },
    { 'relv': 'zara.josephine04@gmail.com', 'Rel': 'ZARA, ANTONIO A' },
    { 'relv': 'N/A', 'Rel': 'NABUA, CARMELA C' },
    { 'relv': 'N/A', 'Rel': 'SISON, MEREGIN V' },
    { 'relv': 'MarkLesterViray@yahoo.com', 'Rel': 'VIRAY, MARK LESTER L' },
    { 'relv': 'raymundpdelacruz@gmail.com', 'Rel': 'DELA CRUZ, RAYMUND P' },
    { 'relv': 'N/A', 'Rel': 'SALAZAR, JULIETA R' },
    { 'relv': 'joyabad171976@yahoo.com', 'Rel': 'ABAD, JOY C' },
    { 'relv': 'agonoymargarita@yahoo.com', 'Rel': 'AGONOY, MARGARITA T' },
    { 'relv': 'noveroevelyn@yahoo.com', 'Rel': 'CATABAY, EVELYN N' },
    { 'relv': 'N/A', 'Rel': 'AQUINO, LEONARD G' },
    { 'relv': 'N/A', 'Rel': 'DAGMANTE, LIBERTY L' },
    { 'relv': 'N/A', 'Rel': 'CARIDAD, BERNARD M' },
    { 'relv': 'N/A', 'Rel': 'FERNANDEZ, JOSHUA V' },
    { 'relv': 'N/A', 'Rel': 'SALAZAR, JULIE JEAN L' },
    { 'relv': 'fretztan@yahoo.com', 'Rel': 'TAN, FREDEZMINDA D' },
    { 'relv': 'hacimeg07@gmail.com', 'Rel': 'FERNANDEZ, MA. GEMICAH O' },
    { 'relv': 'N/A', 'Rel': 'GRANADO, CORAZON S' },
    { 'relv': 'N/A', 'Rel': 'DAZO, RUMER I' },
    { 'relv': 'alliemacaraeg1981@gmail.com', 'Rel': 'MACARAEG, ALLIE D' },
    { 'relv': 'N/A', 'Rel': 'OBALDO, ALICIA A' },
    { 'relv': 'chingching0516@gmail.com', 'Rel': 'PADILLA, JOCELYN R' },
    { 'relv': 'N/A', 'Rel': 'PALOMAR, JEAN ANGELICA F' },
    { 'relv': 'ramilbulandan1979@gmail.com.ph', 'Rel': 'BULANDAN, RAMIL A' },
    { 'relv': 'jmanaois76@gmail.com', 'Rel': 'MANAOIS, JERRY A' },
    { 'relv': 'melvinparagas965@gmail.com', 'Rel': 'PARAGAS, MELVIN A' },
    { 'relv': 'cristina.pamilihan2go@gmail.com', 'Rel': 'OROLFO, CRISTINA B' },
    { 'relv': 'hyradomingo6@gmail.com', 'Rel': 'VALENZUELA, JENNY D' },
    { 'relv': 'N/A', 'Rel': 'DALUMPINES, RODELITA A' },
    { 'relv': 'antonio.elyjr@gmail.com', 'Rel': 'ELY, ANTONIO JR P' },
    { 'relv': 'N/A', 'Rel': 'ESPARTERO, REYNOLD A' },
    { 'relv': 'N/A', 'Rel': 'HUBABIB, ROGELIO A' },
    { 'relv': 'N/A', 'Rel': 'IGAMINO, RICARDO JR P' },
    { 'relv': 'mannymenguito2018@gmail.com', 'Rel': 'MENGUITO, EMMANUEL S' },
    { 'relv': 'N/A', 'Rel': 'MENGUITO, FEB ARTHUR C' },
    { 'relv': 'paniezaelner01@gmail.com', 'Rel': 'PANIEZA, ELNER P' },
    { 'relv': 'N/A', 'Rel': 'POLINIO, THELMA B' },
    { 'relv': 'nionilocv@gmail.com', 'Rel': 'VILLANUEVA, NIONILO C' },
];

function populateAgentDropdown(e) {
    $(e).empty();
    e.append($('<option></option>').val('').text('Select Agent Name'));
    agentdata.forEach(function (v) {
        e.append($('<option></option>').val(v.relv).text(v.Rel));
    });
}
