let countrydata = [
    { 'Country': 'AFGHANISTAN' },
    { 'Country': 'ÅLAND ISLANDS' },
    { 'Country': 'ALBANIA' },
    { 'Country': 'ALGERIA' },
    { 'Country': 'AMERICAN SAMOA' },
    { 'Country': 'ANDORRA' },
    { 'Country': 'ANGOLA' },
    { 'Country': 'ANGUILLA' },
    { 'Country': 'ANTARCTICA' },
    { 'Country': 'ANTIGUA AND BARBUDA' },
    { 'Country': 'ARGENTINA' }, 
    { 'Country': 'ARMENIA' },
    { 'Country': 'ARUBA' },
    { 'Country': 'AUSTRALIA' },
    { 'Country': 'AUSTRIA' },
    { 'Country': 'AZERBAIJAN' },
    { 'Country': 'BAHAMAS' },
    { 'Country': 'BAHRAIN' },
    { 'Country': 'BANGLADESH' },
    { 'Country': 'BARBADOS' },
    { 'Country': 'BELARUS' },
    { 'Country': 'BELGIUM' },
    { 'Country': 'BELIZE' },
    { 'Country': 'BENIN' },
    { 'Country': 'BERMUDA' },
    { 'Country': 'BHUTAN' },
    { 'Country': 'BOLIVIA' },
    { 'Country': 'BOSNIA AND HERZEGOVINA' },
    { 'Country': 'BOTSWANA' },
    { 'Country': 'BOUVET ISLAND' },
    { 'Country': 'BRAZIL' },
    { 'Country': 'BRITISH INDIAN OCEAN TERRITORY' },
    { 'Country': 'BRUNEI DARUSSALAM' },
    { 'Country': 'BULGARIA' },
    { 'Country': 'BURKINA FASO' },
    { 'Country': 'BURUNDI' },
    { 'Country': 'CAMBODIA' },
    { 'Country': 'CAMEROON' },
    { 'Country': 'CANADA' },
    { 'Country': 'CAPE VERDE' },
    { 'Country': 'CAYMAN ISLANDS' },
    { 'Country': 'CENTRAL AFRICAN REPUBLIC' },
    { 'Country': 'CHAD' },
    { 'Country': 'CHILE' },
    { 'Country': 'CHINA' },
    { 'Country': 'CHRISTMAS ISLAND' },
    { 'Country': 'COCOS (KEELING) ISLANDS' },
    { 'Country': 'COLOMBIA' },
    { 'Country': 'COMOROS' },
    { 'Country': 'CONGO' },
    { 'Country': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
    { 'Country': 'COOK ISLANDS' },
    { 'Country': 'COSTA RICA' },
    { 'Country': "COTE D'IVOIRE" },
    { 'Country': 'CROATIA' },
    { 'Country': 'CUBA' },
    { 'Country': 'CYPRUS' },
    { 'Country': 'CZECHIA' },
    { 'Country': 'DENMARK' },
    { 'Country': 'DJIBOUTI' },
    { 'Country': 'DOMINICA' },
    { 'Country': 'DOMINICAN REPUBLIC' },
    { 'Country': 'ECUADOR' },
    { 'Country': 'EGYPT' },
    { 'Country': 'EL SALVADOR' },
    { 'Country': 'EQUATORIAL GUINEA' },
    { 'Country': 'ERITREA' },
    { 'Country': 'ESTONIA' },
    { 'Country': 'ETHIOPIA' },
    { 'Country': 'FALKLAND ISLANDS (MALVINAS)' },
    { 'Country': 'FAROE ISLANDS' },
    { 'Country': 'FIJI' },
    { 'Country': 'FINLAND' },
    { 'Country': 'FRANCE' },
    { 'Country': 'FRENCH GUIANA' },
    { 'Country': 'FRENCH POLYNESIA' },
    { 'Country': 'FRENCH SOUTHERN TERRITORIES' },
    { 'Country': 'GABON' },
    { 'Country': 'GAMBIA' },
    { 'Country': 'GEORGIA' },
    { 'Country': 'GERMANY' },
    { 'Country': 'GHANA' },
    { 'Country': 'GIBRALTAR' },
    { 'Country': 'GREECE' },
    { 'Country': 'GREENLAND' },
    { 'Country': 'GRENADA' },
    { 'Country': 'GUADELOUPE' },
    { 'Country': 'GUAM' },
    { 'Country': 'GUATEMALA' },
    { 'Country': 'GUERNSEY' },
    { 'Country': 'GUINEA' },
    { 'Country': 'GUINEA-BISSAU' },
    { 'Country': 'GUYANA' },
    { 'Country': 'HAITI' },
    { 'Country': 'HEARD ISLAND AND MCDONALD ISLANDS' },
    { 'Country': 'HOLY SEE (VATICAN CITY STATE)' },
    { 'Country': 'HONDURAS' },
    { 'Country': 'HONG KONG' },
    { 'Country': 'HUNGARY' },
    { 'Country': 'ICELAND' },
    { 'Country': 'INDIA' },
    { 'Country': 'INDONESIA' },
    { 'Country': 'IRAN, ISLAMIC REPUBLIC OF' },
    { 'Country': 'IRAQ' },
    { 'Country': 'IRELAND' },
    { 'Country': 'ISLE OF MAN' },
    { 'Country': 'ISRAEL' },
    { 'Country': 'ITALY' },
    { 'Country': 'JAMAICA' },
    { 'Country': 'JAPAN' },
    { 'Country': 'JERSEY' },
    { 'Country': 'JORDAN' },
    { 'Country': 'KAZAKHSTAN' },
    { 'Country': 'KENYA' },
    { 'Country': 'KIRIBATI' },
    { 'Country': "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" },
    { 'Country': 'KOREA, REPUBLIC OF' },
    { 'Country': 'KUWAIT' },
    { 'Country': 'KYRGYZSTAN' },
    { 'Country': "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
    { 'Country': 'LATVIA' },
    { 'Country': 'LEBANON' },
    { 'Country': 'LESOTHO' },
    { 'Country': 'LIBERIA' },
    { 'Country': 'LIBYAN ARAB JAMAHIRIYA' },
    { 'Country': 'LIECHTENSTEIN' },
    { 'Country': 'LITHUANIA' },
    { 'Country': 'LUXEMBOURG' },
    { 'Country': 'MACAO' },
    { 'Country': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
    { 'Country': 'MADAGASCAR' },
    { 'Country': 'MALAWI' },
    { 'Country': 'MALAYSIA' },
    { 'Country': 'MALDIVES' },
    { 'Country': 'MALI' },
    { 'Country': 'MALTA' },
    { 'Country': 'MARSHALL ISLANDS' },
    { 'Country': 'MARTINIQUE' },
    { 'Country': 'MAURITANIA' },
    { 'Country': 'MAURITIUS' },
    { 'Country': 'MAYOTTE' },
    { 'Country': 'MEXICO' },
    { 'Country': 'MICRONESIA, FEDERATED STATES OF' },
    { 'Country': 'MOLDOVA, REPUBLIC OF' },
    { 'Country': 'MONACO' },
    { 'Country': 'MONGOLIA' },
    { 'Country': 'MONTENEGRO' },
    { 'Country': 'MONTSERRAT' },
    { 'Country': 'MOROCCO' },
    { 'Country': 'MOZAMBIQUE' },
    { 'Country': 'MYANMAR' },
    { 'Country': 'NAMIBIA' },
    { 'Country': 'NAURU' },
    { 'Country': 'NEPAL' },
    { 'Country': 'NETHERLANDS' },
    { 'Country': 'NETHERLANDS ANTILLES' },
    { 'Country': 'NEW CALEDONIA' },
    { 'Country': 'NEW ZEALAND' },
    { 'Country': 'NICARAGUA' },
    { 'Country': 'NIGER' },
    { 'Country': 'NIGERIA' },
    { 'Country': 'NIUE' },
    { 'Country': 'NORFOLK ISLAND' },
    { 'Country': 'NORTHERN MARIANA ISLANDS' },
    { 'Country': 'NORWAY' },
    { 'Country': 'OMAN' },
    { 'Country': 'PAKISTAN' },
    { 'Country': 'PALAU' },
    { 'Country': 'PALESTINIAN TERRITORY, OCCUPIED' },
    { 'Country': 'PANAMA' },
    { 'Country': 'PAPUA NEW GUINEA' },
    { 'Country': 'PARAGUAY' },
    { 'Country': 'PERU' },
    { 'Country': 'PHILIPPINES' },
    { 'Country': 'PITCAIRN' },
    { 'Country': 'POLAND' },
    { 'Country': 'PORTUGAL' },
    { 'Country': 'PUERTO RICO' },
    { 'Country': 'QATAR' },
    { 'Country': 'REUNION' },
    { 'Country': 'ROMANIA' },
    { 'Country': 'RUSSIAN FEDERATION' },
    { 'Country': 'RWANDA' },
    { 'Country': 'SAINT HELENA' },
    { 'Country': 'SAINT KITTS AND NEVIS' },
    { 'Country': 'SAINT LUCIA' },
    { 'Country': 'SAINT PIERRE AND MIQUELON' },
    { 'Country': 'SAINT VINCENT AND THE GRENADINES' },
    { 'Country': 'SAMOA' },
    { 'Country': 'SAN MARINO' },
    { 'Country': 'SAO TOME AND PRINCIPE' },
    { 'Country': 'SAUDI ARABIA' },
    { 'Country': 'SENEGAL' },
    { 'Country': 'SERBIA' },
    { 'Country': 'SEYCHELLES' },
    { 'Country': 'SIERRA LEONE' },
    { 'Country': 'SINGAPORE' },
    { 'Country': 'SLOVAKIA' },
    { 'Country': 'SLOVENIA' },
    { 'Country': 'SOLOMON ISLANDS' },
    { 'Country': 'SOMALIA' },
    { 'Country': 'SOUTH AFRICA' },
    { 'Country': 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
    { 'Country': 'SPAIN' },
    { 'Country': 'SRI LANKA' },
    { 'Country': 'SUDAN' },
    { 'Country': 'SURINAME' },
    { 'Country': 'SVALBARD AND JAN MAYEN' },
    { 'Country': 'SWAZILAND' },
    { 'Country': 'SWEDEN' },
    { 'Country': 'SWITZERLAND' },
    { 'Country': 'SYRIAN ARAB REPUBLIC' },
    { 'Country': 'TAIWAN, PROVINCE OF CHINA' },
    { 'Country': 'TAJIKISTAN' },
    { 'Country': 'TANZANIA, UNITED REPUBLIC OF' },
    { 'Country': 'THAILAND' },
    { 'Country': 'TIMOR-LESTE' },
    { 'Country': 'TOGO' },
    { 'Country': 'TOKELAU' },
    { 'Country': 'TONGA' },
    { 'Country': 'TRINIDAD AND TOBAGO' },
    { 'Country': 'TUNISIA' },
    { 'Country': 'TURKEY' },
    { 'Country': 'TURKMENISTAN' },
    { 'Country': 'TURKS AND CAICOS ISLANDS' },
    { 'Country': 'TUVALU' },
    { 'Country': 'UGANDA' },
    { 'Country': 'UKRAINE' },
    { 'Country': 'UNITED ARAB EMIRATES' },
    { 'Country': 'UNITED KINGDOM' },
    { 'Country': 'UNITED STATES' },
    { 'Country': 'UNITED STATES MINOR OUTLYING ISLANDS' },
    { 'Country': 'URUGUAY' },
    { 'Country': 'UZBEKISTAN' },
    { 'Country': 'VANUATU' },
    { 'Country': 'VENEZUELA' },
    { 'Country': 'VIET NAM' },
    { 'Country': 'VIRGIN ISLANDS, BRITISH' },
    { 'Country': 'VIRGIN ISLANDS, U.S.' },
    { 'Country': 'WALLIS AND FUTUNA' },
    { 'Country': 'WESTERN SAHARA' },
    { 'Country': 'YEMEN' },
    { 'Country': 'ZAMBIA' },
    { 'Country': 'ZIMBABWE' },
];

function populateCountryDropdown(e) {
    countrydata.forEach(function (v) {
        //$('#' + eid).append($('<option></option>').val(e.Rel).text(e.Rel));
        if (v.Country == 'Philippines') { e.append($('<option selected></option>').val(v.Country).text(v.Country)); }
        else { e.append($('<option></option>').val(v.Country).text(v.Country)); }
    });
}
